# Configuração de indicadores para análise ex-ante e ex-post da Ata do Copom
# Preencha/ajuste os códigos de séries do SGS conforme necessário.

referencia:
  data_ata: "2005-01-27"   # data da ata referência (YYYY-MM-DD)
  janela_meses_pre: 12
  janela_meses_pos: 12

indicadores:
  - nome: "IPCA"
    focus:
      type: "annual"
      indic: "IPCA"
      filter: "baseCalculo eq 0"
    sgs:
      series_id: 433            # IPCA variação mensal (%)
      compute_12m_percent: true # calcula acumulado 12m com base na var. mensal
      value_name: "IPCA"
      real_col: "IPCA_12m"
      legend_label: "IPCA Realizado 12m"
      y_label: "Inflação (%)"
    title: "Impacto da ata do Copom nas expectativas de inflação"
    subtitle: "Expectativas do Focus (12m) vs IPCA acumulado em 12m"

  - nome: "Selic"
    focus:
      type: "annual"
      indic: "SELIC"
      filter: "baseCalculo eq 0"
    sgs:
      series_id: 432            # Selic meta (% a.a.)
      compute_12m_percent: false
      value_name: "Selic"
      real_col: "Selic"
      legend_label: "Selic (% a.a.)"
      y_label: "Selic (% a.a.)"
    title: "Ata do Copom e trajetória da Selic"
    subtitle: "Expectativas do Focus (12m) vs Selic (SGS)"

  - nome: "Cambio"
    # Sem expectativas Focus por padrão
    sgs:
      series_id: 1              # AJUSTAR: série de câmbio desejada
      compute_12m_percent: false
      value_name: "Cambio"
      real_col: "Cambio"
      legend_label: "R$/US$"
      y_label: "R$/US$"
    title: "Ata do Copom e taxa de câmbio"
    subtitle: "Câmbio nominal (SGS)"

  - nome: "Desemprego"
    sgs:
      series_id: 4099           # AJUSTAR: desemprego (PNAD Contínua) se disponível
      compute_12m_percent: false
      value_name: "Desemprego"
      real_col: "Desemprego"
      legend_label: "Desemprego (%)"
      y_label: "Desemprego (%)"
    title: "Ata do Copom e desemprego"
    subtitle: "Taxa de desemprego (SGS)"

  - nome: "PIB_Trimestral"
    sgs:
      series_id: 4380           # AJUSTAR: crescimento trimestral do PIB (%), se disponível
      compute_12m_percent: false
      value_name: "PIB"
      real_col: "PIB"
      legend_label: "PIB trimestral (%)"
      y_label: "PIB trimestral (%)"
    title: "Ata do Copom e PIB trimestral"
    subtitle: "Crescimento do PIB trimestral (SGS)"

  - nome: "Meta_Inflacao"
    sgs:
      series_id: 13522          # AJUSTAR: meta de inflação (%)
      compute_12m_percent: false
      value_name: "Meta"
      real_col: "Meta"
      legend_label: "Meta de Inflação (%)"
      y_label: "Meta de Inflacão (%)"
    title: "Ata do Copom e meta de inflação"
    subtitle: "Meta para o ano-calendário (SGS)"

  - nome: "Deficit_Primario"
    sgs:
      series_id: 4513           # AJUSTAR: resultado primário (% PIB) ou R$ mi
      compute_12m_percent: false
      value_name: "Primario"
      real_col: "Primario"
      legend_label: "Resultado Primário"
      y_label: "Resultado Primário"
    title: "Ata do Copom e resultado primário"
    subtitle: "Déficit/superávit primário (SGS)"
